### ISSUE TITLE
Make access logging output configurable

### ISSUE THREAD

**Issue by dcseifert** [Foundato/kelon#116]
Right now Kelon logs three messages for each processed http request with logging level INFO. In order to enable the reduction of this log-bloat, a flag should be added which enables the administrator of Kelon to reduce these log messages.

Following enum-values should be possible:
- **ALL**: Log all messages
- **ALLOW**: Only log requests that were allowed
- **DENY**: Only log requests that were denied
- **NONE**: Log no requests

The logging messages should also be reduced to one message which contains the following fields: 
- **PATH** (The URL from the processed request)
- **METHOD** (HTTP-Method of the processed request
- **DURATION** (Duration of the entire request processing in milliseconds)
- **DECISION** (Decision for the incoming request: ALLOW or DENY)

Following tasks have to be completed
- [x] Reduce logs to specified format
- [x] Make logged output configurable
- [x] Adjust [Kelon Docs](https://docs.kelon.io/operations/Configuration/)

**Comment by dcseifert** [comment]
@containerpope spec valid?

**Comment by containerpope** [comment]
@dcseifert valid 👍🏻
