### ISSUE TITLE
Explore external interfaces

### ISSUE THREAD

**Issue by dcseifert** [Foundato/kelon#3]
# Description
Explore all external interfaces of the agent. This is an important initial step of finding out all available information that have to be connected via the config file.

# Outcome
Full understanding and documentation of:
- [x] OPA interfaces 
- [x] Usage discovery of OPA's interface in existing projects
- [x] Incoming user request structure (Http...)
- [x] Connection to datastores

**Comment by mkjoerg** [comment]
@dcseifert Approved
