### ISSUE TITLE
Istio external auth compability

### ISSUE THREAD

**Issue by mkjoerg** [Foundato/kelon#30]
To make kelon work out of the box with Istio, we need to provide a GRPC endpoint for Istio external auth plugin. The details can be inspected here: https://github.com/open-policy-agent/opa-istio-plugin

This will allow us to forward auth requests from Istio Sidecars directly to the Kelon project without changing the service code to intercept incoming requests.

**Comment by mkjoerg** [comment]
@dcseifert Implementing this with Istio and a custom Envoy Filter rule is a dangerous process and should maybe be delayed in favor of other simpler implementations. We should try Gloo first. #42

**Comment by dcseifert** [comment]
Sounds like a good idea.
