### ISSUE TITLE
Design agent architecture

### ISSUE THREAD

**Issue by dcseifert** [Foundato/kelon#4]
# Description
With modular datastores in mind we need to define a concept for the entire agent.

# Outcome
- [x] System which is capable of loading external "datastore plugins"
- [x] System for live-reloading of configuration
- [x] Documented top-level software architecture (including module structure)
- [x] Minimal implementation to verify functionality

**Comment by dcseifert** [comment]
Component diagram which meets outcomes 1-3 created in [Wiki -> Software design -> Components](https://github.com/Foundato/kelon/wiki/Component-diagram)

**Comment by dcseifert** [comment]
Plugins can be easily integrated via [Go plugins](https://medium.com/learning-the-go-programming-language/writing-modular-go-programs-with-plugins-ec46381ee1a9)

The config (which plugin to load) can be provided as yaml/main-args

**Comment by dcseifert** [comment]
Also have a look at this illustration of the internal [API transformation](https://github.com/Foundato/kelon/wiki/Internal-API-transformation)

**Comment by mkjoerg** [comment]
@dcseifert  Closing, because already finished
