### ISSUE TITLE
Implement Kelon as out of tree Istio Mixer Plugin

### ISSUE THREAD

**Issue by mkjoerg** [Foundato/kelon#43]
## Proposal
Kelon could be a perfect fit to be implemented as out of tree mixer plugin. 

https://istio.io/docs/reference/config/policy-and-telemetry/mixer-overview/
https://venilnoronha.io/set-sail-a-production-ready-istio-adapter
https://github.com/istio/istio/wiki/Mixer-Out-Of-Process-Adapter-Walkthrough

## Requirements:

Istio relies at the adapter side on different CRDs, that allow forwarding each matching request to a custom out of tree adapter by a gRPC endpoint. 
The CRDs are displayed here:
![image](https://user-images.githubusercontent.com/12080409/70166464-1bdc1d00-16c5-11ea-8502-f991f0f91209.png)
See https://istio.io/docs/reference/config/policy-and-telemetry/mixer-overview/ for more details.

There is a specific Instance type for authorization available in Istio:
![image](https://user-images.githubusercontent.com/12080409/70167019-221ec900-16c6-11ea-873b-b8e3a2655ffa.png)
https://istio.io/docs/reference/config/policy-and-telemetry/templates/authorization/

This seems to provide all elements, but the body. 

Implementing this on Kelons side should be very easy, because Kelon just requires a new gRPC endpoint that can handle the input provided by the Istio Handler CRD. More difficult is to find out if we can meet the requirements:

### Rule Requirements:
* Requests can be matched by uri and method

### Mapper Requirements:
* Request headers and path can be forwarded to Kelon
* ~~Request body can be forwarded to Kelon~~

## Deliverables:
- [x] Research on Rule and Mapper requirements
- [x] Implement gRPC out of tree adapter interface to Kelon
- [x] Encrypt connection between Mixer and GRPC adapter

**Comment by mkjoerg** [comment]
@dcseifert Do you approve ?

**Comment by dcseifert** [comment]
@mkjoerg Approved
I would say that we keep this issue for the next milestone. Let's now focus on the first release.

**Comment by mkjoerg** [comment]
@dcseifert as stated in slack, maybe a good option to gather fast test feedback

**Comment by mkjoerg** [comment]
@dcseifert Authorization instance type seems not to be able to forward the body to the adapter, so this is a downside, but should not affect the general implementation possibility.

**Comment by dcseifert** [comment]
Basic implementation is finished, but currently I am unable to test it on my local machine.
Seems to be a configuration issue with Istio!

Issue in Istio-Project created [here](https://github.com/istio/istio/issues/19573)
