### ISSUE TITLE
Determine configuration process

### ISSUE THREAD

**Issue by dcseifert** [Foundato/kelon#5]
# Description
In order to connect all external interface the agent needs some kind of config structure that is needed to gather all needed information to perform the final OPA call.

# Outcome
- [x] Analyze amount of needed configs (In correlation to the datastores)
- [x] Documented config structure (embedded in external interfaces)
- [x] Example config
- [x] Design and document config processing
- [x] Implement config processing
- [x] Analyze config management in connection with Kubernetes (secret, config-map, env-vars)
- [x] Concept for global and scoped policies

**Comment by dcseifert** [comment]
Configuration can be done via a custom ConfigParser which uses i.e. available environment vars

**Comment by mkjoerg** [comment]
@dcseifert Approved
