### ISSUE TITLE
Allow setting sql parameters in datastore config

### ISSUE THREAD

**Issue by mkjoerg** [Foundato/kelon#51]
Kelon currently does not support setting connection parameters and this leads to problems if people want to connect their databases.

## Acceptance Criteria
* Allow setting connection parameters for datastores
* Allow setting ssl options for postgres & mysql
* Found generic way of providing connection parameters

**Comment by mkjoerg** [comment]
@dcseifert What do you think about this?

**Comment by dcseifert** [comment]
Sounds great, I'll just add the possibility to add any additional key-value-pair provided in datastore-connection as connection option.
