### ISSUE TITLE
Allow different ways of setting datastore secrets

### ISSUE THREAD

**Issue by mkjoerg** [Foundato/kelon#52]
## Description
At the moment secrets are written in plain text into the datastore config yaml. This leads to problems in deployment, because the config should then be deployed as k8s secret for example because it contains sensitive data. 

### Proposals:
Separate option to provide files containing the secret information. These files could then be mounted as secrets into the pod.

**Comment by mkjoerg** [comment]
@dcseifert what do you think ?

**Comment by dcseifert** [comment]
@mkjoerg  With my latest commit for this issue, the datastore.yml-file can be expanded via environment variables. Therefore Secrets could be injected via [Mounting a k8s secret as environment variable](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)

Does that also satisfy our needs, or is additional externalization into a file needed?

**Comment by dcseifert** [comment]
Closing this issue after a discussion with #56 as optional further enhancement.
