### ISSUE TITLE
Kelon performance metrics

### ISSUE THREAD

**Issue by containerpope** [Foundato/kelon#79]
## Problem Statement
Common questions asked when operating the system are:

- Are there an increase in failures while executing policies ?
- Are policies performing poorly? -> Increase in latency ?

## Suggested Solution
To answer all these questions easily, we can implement prometheus metrics that represent exactly that information.
Suggestion would be to provide (counter & summary) metrics for each processed request with the following labels:

- ~~package~~
- ~~request path~~
- request method
- ~~result (granted, denied, error)~~

This would allow to monitor latency and error rate of kelon.

**Comment by mkjoerg** [comment]
@dcseifert what do you think?

**Comment by mkjoerg** [comment]
Decided not to include request path and package, result is represented by status code if toggled. Also removed database metrics
