### ISSUE TITLE
Create demo environment

### ISSUE THREAD

**Issue by dcseifert** [Foundato/kelon#8]
# Description
Setup a demo environment which contains an example application (datastore, backend and optionally frontend) to evaluate the functionality of the policy enforcement.

# Outcome
Ready to use demo environment for testing kelon.

**Comment by dcseifert** [comment]
This is the optimal demo application to show the capabilities of our tool:
https://github.com/gothinkster/realworld

**Comment by mkjoerg** [comment]
@dcseifert can this be closed ? Due to the fact, that we have the example repo now.

**Comment by dcseifert** [comment]
@mkjoerg You are right!
