### ISSUE TITLE
Add request UID to logging

### ISSUE THREAD

**Issue by dcseifert** [Foundato/kelon#81]
# Description

It is impossible to determine all logs for one particular request when parallel requests are made agains Kelon. Therefore one UID should be created for each incoming request which should be logged from this time on.

**Comment by mkjoerg** [comment]
@dcseifert closing this, due to uid already in logs :) 

```log
INFO[2020-06-28T12:02:23+02:00] Partial Evaluation for "data.applications.pg.allow == true" with extractedInput: map[method:GET path:[api pg apps 1] queries:map[] user:Test]Returned 4 queries:  UID=4926a615-93ef-434c-9d02-13b6898b491d
INFO[2020-06-28T12:02:23+02:00] Decision: ALLOW                               UID=4926a615-93ef-434c-9d02-13b6898b491d
```
